### ISSUE TITLE
Your navbar drawer section is behind the components menu in mobile view

### ISSUE THREAD

**Issue by keshavkumar-in** [smilegupta/style-ship#48]
Your navbar drawer section is behind the components menu in mobile view, you can change the drawer `z-index` value to `2` and on the sidebar section, you should change the `z-index` value to `1` to solve this issue.

![Smile](https://user-images.githubusercontent.com/14369793/153758494-dce81f3e-1b10-4ee8-8595-97f5fa1293b1.png)
https://github.com/smilegupta/style-ship/blob/13b6190d85745d3f280a6635a94107a0d76bccbf/styles/navbar.css#L56
https://github.com/smilegupta/style-ship/blob/13b6190d85745d3f280a6635a94107a0d76bccbf/styles/sidebar.css#L6

**Comment by smilegupta** [comment]
Done #49
